ALTER TABLE calendar_events 
  ADD COLUMN IF NOT EXISTS reminder_sent_24h BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS reminder_sent_2h BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS no_show_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS requires_confirmation BOOLEAN DEFAULT FALSE;