// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// IMPORTANT: Use environment variables instead of hardcoded values
// The values below should come from .env.local for proper environment separation
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://hantkriglxwmddbpddnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhbnRrcmlnbHh3bWRkYnBkZG53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcwNzkzODcsImV4cCI6MjA4MjY1NTM4N30.PfH8SnoaOCSQOGEMWOsRgRZH9UyggeQQIiZ6Elqlvtw";

// Validate environment variables
if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
  console.warn('⚠️ Supabase environment variables not found. Using fallback values from client.ts');
  console.warn('⚠️ Please ensure .env.local is properly configured with:');
  console.warn('   - NEXT_PUBLIC_SUPABASE_URL');
  console.warn('   - NEXT_PUBLIC_SUPABASE_ANON_KEY');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a singleton instance with proper configuration and error handling
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
      // Handle storage errors gracefully
      storage: {
        getItem: (key: string) => {
          try {
            return localStorage.getItem(key);
          } catch (error) {
            console.error('Error reading from localStorage:', error);
            return null;
          }
        },
        setItem: (key: string, value: string) => {
          try {
            localStorage.setItem(key, value);
          } catch (error) {
            console.error('Error writing to localStorage:', error);
          }
        },
        removeItem: (key: string) => {
          try {
            localStorage.removeItem(key);
          } catch (error) {
            console.error('Error removing from localStorage:', error);
          }
        },
      },
    },
    global: {
      headers: {
        'X-Client-Info': 'supabase-js-web',
      },
    },
  }
);

// Handle auth errors globally
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'TOKEN_REFRESHED') {
    console.log('✅ Token refreshed successfully');
  }
  
  if (event === 'SIGNED_OUT') {
    console.log('👋 User signed out');
    // Clear any stale data
    if (typeof window !== 'undefined') {
      try {
        localStorage.removeItem('supabase.auth.token');
      } catch (error) {
        console.error('Error clearing auth token:', error);
      }
    }
  }
  
  // Handle token refresh errors
  if (event === 'USER_UPDATED' && !session) {
    console.warn('⚠️ Session lost - user needs to re-authenticate');
  }
});

// Add error interceptor for auth errors
const originalFrom = supabase.from.bind(supabase);
supabase.from = ((table: string) => {
  const query = originalFrom(table);
  
  // Intercept errors
  const originalThen = query.then?.bind(query);
  if (originalThen) {
    query.then = function(onFulfilled?: any, onRejected?: any) {
      return originalThen(
        (value: any) => {
          // Check for auth errors in response
          if (value?.error?.message?.includes('refresh_token')) {
            console.error('🔴 Refresh token error detected - clearing session');
            handleSessionExpired();
          }
          return onFulfilled ? onFulfilled(value) : value;
        },
        onRejected
      );
    };
  }
  
  return query;
}) as any;

// Handle expired sessions
function handleSessionExpired() {
  if (typeof window !== 'undefined') {
    try {
      // Clear all auth-related data
      localStorage.removeItem('supabase.auth.token');
      
      // Sign out silently
      supabase.auth.signOut({ scope: 'local' }).catch(() => {
        // Ignore errors during cleanup
      });
      
      // Redirect to login
      const currentPath = window.location.pathname;
      if (currentPath !== '/login' && currentPath !== '/') {
        window.location.href = '/login';
      }
    } catch (error) {
      console.error('Error handling session expiration:', error);
    }
  }
}